name: DiscordEventSync
version: '${project.version}'
main: nl.thedutchruben.discordeventsync.DiscordEventSync
authors: [ TheDuchRuben, wouter_MC ]
description: Sync the events of discord to minecraft
website: www.thedutchruben.nl
commands:
  discordevent:
    aliases:
      - dce
  discord:
    aliases:
      - dc